---
title: "SpikeStats"
output: html_notebook
---

```{r}
library(duckdb)

# Connect to database file
con <- dbConnect(duckdb(), dbdir = ":memory:", read_only = FALSE)
```

```{r}
# Import all matches into a table
all_plays_csv = read.csv("../data/matches/all_matches.csv")[,-1]
dbWriteTable(con, "all_plays", all_plays_csv, overwrite = TRUE)
```

```{r}
# Query to retrieve all rows matching the green, yellow, and orange cells in the EF Data Volley Grade Grid
dbGetQuery(con, "SELECT *
           FROM all_plays 
           WHERE evaluation_code == '=' OR
           (evaluation_code == '#' AND skill IN ('Serve', 'Attack', 'Block'))")
```

```{r}
# Query to retrieve the relevant columns for all rows matching the green, yellow, and orange cells in the EF Data Volley Grade Grid
dbGetQuery(con, "SELECT skill,  evaluation_code, team_id_wonlost_set, won_match, season, match_set
           FROM all_plays 
           WHERE evaluation_code == '=' OR
           (evaluation_code == '#' AND skill IN ('Serve', 'Attack', 'Block'))")
```


```{r}
dbGetQuery(con, "SELECT *
           FROM all_plays 
           WHERE evaluation_code == '=' AND
           skill == 'Recieve'")
dbGetQuery(con, "SELECT DISTINCT skill FROM all_plays WHERE evaluation_code == '='")
```


