---
title: "Initial Regression"
output: html_document
date: "2024-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load data
df = read.csv('../data/matches/all_matches_processed.csv')
df$wonSet = as.factor(df$wonSet)
head(df)
sum(df$earnedPts)
```

```{r}
df[482,]
# 14 additional points scored above typical (32-30 sets, rows 482, 497)
```

```{r}
# Fit initial glm for sanity check
glm1 = glm(wonSet ~ unforcedErrs + earnedPts, df, family="binomial")
summary(glm1)
```

```{r}
err_conf = -rev(confint(glm1, 'unforcedErrs', 0.90))
earned_conf = confint(glm1, 'earnedPts', 0.90)
print(err_conf)
print(earned_conf)
```

```{r}
plot(glm1)
```



```{r}
glm2 = glm(wonSet ~ serveErr + setErr + attackErr + freeballErr + ace + kill + stuffBlock, df, family="binomial")
summary(glm2)
```

```{r}
cor(df[,8:14])
```


```{r}
glm3 = glm(wonSet ~ serveErr + setErr + attackErr + ace + kill + stuffBlock, df, family="binomial")
summary(glm3)
```

```{r}
glm4 = glm(wonSet ~ serveErr + attackErr + ace + kill + stuffBlock, df, family="binomial")
summary(glm4)
```

